USE [master]
GO

/****** Object:  Database [Minsait]    Script Date: 18/11/2021 01:11:01 p. m. ******/
CREATE DATABASE [Minsait]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Minsait', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Minsait.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Minsait_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Minsait_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Minsait].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Minsait] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Minsait] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Minsait] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Minsait] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Minsait] SET ARITHABORT OFF 
GO

ALTER DATABASE [Minsait] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Minsait] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Minsait] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Minsait] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Minsait] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Minsait] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Minsait] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Minsait] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Minsait] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Minsait] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Minsait] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Minsait] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Minsait] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Minsait] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Minsait] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Minsait] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Minsait] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Minsait] SET RECOVERY FULL 
GO

ALTER DATABASE [Minsait] SET  MULTI_USER 
GO

ALTER DATABASE [Minsait] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Minsait] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Minsait] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Minsait] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Minsait] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Minsait] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Minsait] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Minsait] SET  READ_WRITE 
GO


