USE [Minsait]
GO

INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('AUSTRIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BELGICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BULGARIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CHIPRE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('DINAMARCA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ESPAÑA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('FINLANDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('FRANCIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GRECIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('HUNGRIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('IRLANDA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ITALIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LUXEMBURGO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MALTA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PAISES BAJOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('POLONIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PORTUGAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REINO UNIDO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ALEMANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('RUMANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SUECIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LETONIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ESTONIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LITUANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REPUBLICA CHECA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REPUBLICA ESLOVACA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ESLOVENIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ALBANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLANDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LIECHTENSTEIN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MONACO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NORUEGA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ANDORRA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN MARINO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SANTA SEDE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SUIZA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('UCRANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MOLDAVIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BELARUS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GEORGIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BOSNIA Y HERZEGOVINA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CROACIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ARMENIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('RUSIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MACEDONIA ')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SERBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MONTENEGRO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUERNESEY')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SVALBARD Y JAN MAYEN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS FEROE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLA DE MAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GIBRALTAR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS DEL CANAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('JERSEY')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS ALAND')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TURQUIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BURKINA FASO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ANGOLA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ARGELIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BENIN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BOTSWANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BURUNDI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CABO VERDE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CAMERUN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COMORES')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CONGO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COSTA DE MARFIL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('DJIBOUTI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('EGIPTO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ETIOPIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GABON')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GAMBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GHANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUINEA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUINEA-BISSAU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUINEA ECUATORIAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('KENIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LESOTHO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LIBERIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LIBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MADAGASCAR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MALAWI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MALI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MARRUECOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MAURICIO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MAURITANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MOZAMBIQUE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NAMIBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NIGER')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NIGERIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REPUBLICA CENTROAFRICANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SUDAFRICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('RUANDA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SANTO TOME Y PRINCIPE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SENEGAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SEYCHELLES')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SIERRA LEONA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SOMALIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SUDAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SWAZILANDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TANZANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CHAD')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TOGO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TUNEZ')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('UGANDA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REP.DEMOCRATICA DEL CONGO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ZAMBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ZIMBABWE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ERITREA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SANTA HELENA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REUNION')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MAYOTTE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAHARA OCCIDENTAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DE AFRICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CANADA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ESTADOS UNIDOS DE AMERICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MEXICO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN PEDRO Y MIQUELON ')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GROENLANDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ANTIGUA Y BARBUDA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BAHAMAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BARBADOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BELICE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COSTA RICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CUBA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('DOMINICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('EL SALVADOR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GRANADA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUATEMALA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('HAITI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('HONDURAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('JAMAICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NICARAGUA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PANAMA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN VICENTE Y LAS GRANADINAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('REPUBLICA DOMINICANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TRINIDAD Y TOBAGO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SANTA LUCIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN CRISTOBAL Y NIEVES')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS CAIMÁN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS TURCAS Y CAICOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS VÍRGENES DE LOS ESTADOS UNIDOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUADALUPE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ANTILLAS HOLANDESAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN MARTIN (PARTE FRANCESA)')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ARUBA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MONTSERRAT')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ANGUILLA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAN BARTOLOME')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MARTINICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PUERTO RICO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BERMUDAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS VIRGENES BRITANICAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ARGENTINA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BOLIVIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BRASIL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COLOMBIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CHILE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ECUADOR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUYANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PARAGUAY')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PERU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SURINAM')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('URUGUAY')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('VENEZUELA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUAYANA FRANCESA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS MALVINAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS  DE SUDAMERICA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('AFGANISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ARABIA SAUDI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BAHREIN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BANGLADESH')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MYANMAR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CHINA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('EMIRATOS ARABES UNIDOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('FILIPINAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('INDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('INDONESIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('IRAQ')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('IRAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISRAEL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('JAPON')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('JORDANIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('CAMBOYA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('KUWAIT')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LAOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('LIBANO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MALASIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MALDIVAS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MONGOLIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NEPAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OMAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PAKISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('QATAR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COREA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('COREA DEL NORTE ')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SINGAPUR')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SIRIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SRI LANKA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TAILANDIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('VIETNAM')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BRUNEI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS MARSHALL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('YEMEN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('AZERBAIYAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('KAZAJSTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('KIRGUISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TADYIKISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TURKMENISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('UZBEKISTAN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS MARIANAS DEL NORTE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PALESTINA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('HONG KONG')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('BHUTÁN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('GUAM')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MACAO')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DE ASIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('AUSTRALIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('FIJI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NUEVA ZELANDA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PAPUA NUEVA GUINEA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS SALOMON')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAMOA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TONGA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('VANUATU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('MICRONESIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TUVALU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS COOK')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NAURU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('PALAOS')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TIMOR ORIENTAL')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('POLINESIA FRANCESA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLA NORFOLK')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('KIRIBATI')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NIUE')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('ISLAS PITCAIRN')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('TOKELAU')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('NUEVA CALEDONIA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('WALLIS Y FORTUNA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('SAMOA AMERICANA')
INSERT INTO [dbo].[CatPais] ([NombrePais]) VALUES ('OTROS PAISES O TERRITORIOS DE OCEANIA')

GO


