//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinsaitWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.ContactosCliente = new HashSet<ContactosCliente>();
        }
    
        public int IdCliente { get; set; }
        public int IdPais { get; set; }
        public int IdMercado { get; set; }
        public string NombreCliente { get; set; }
        public string IdentificadorFiscal { get; set; }
        public string Email { get; set; }
    
        public virtual CatMercado CatMercado { get; set; }
        public virtual CatPais CatPais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactosCliente> ContactosCliente { get; set; }
    }
}
