//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinsaitWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosCliente
    {
        public int IdContactoCliente { get; set; }
        public int IdCliente { get; set; }
        public string NombreContacto { get; set; }
        public string PuestoContacto { get; set; }
        public string CorreoContacto { get; set; }
        public string NumeroContacto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
